"""Adds repositories/archives."""

########################################################################
# DO NOT EDIT THIS FILE unless you are inside the
# https://github.com/3rdparty/bazel-rules-expected repository. If you
# encounter it anywhere else it is because it has been copied there in
# order to simplify adding transitive dependencies. If you want a
# different version of bazel-rules-expected follow the Bazel build
# instructions at https://github.com/3rdparty/bazel-rules-expected.
########################################################################

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

def repos(external = True, repo_mapping = {}):
    if external:
        maybe(
            git_repository,
            name = "com_github_3rdparty_expected",
            remote = "https://github.com/ArthurBandaruk/bazel-rules-expected",
            commit = "",
            shallow_since = "",
            repo_mapping = repo_mapping,
        )
